#!/bin/sh

# check if svn info available (do not write anything)
svn info 2> /dev/null > /dev/null

if [ $? = 0 ] ; then 
# svn info available: get svn revision
   svn_rev=$(svnversion -n)
else
# svn info available: revert to no info
   svn_rev=unknown
fi
 
# write svn into file .gpu-version.h
cat ../include/gpu-version.h.in | sed 's/unknown/'$svn_rev'/' > ../include/.gpu-version.h.tmp

# check if a previous gpu-version.h file exists
if test -f ../include/gpu-version.h ; then

# gpu-version.h existing: check if new and previous files differ
   diff -wib ../include/.gpu-version.h.tmp ../include/gpu-version.h  2> /dev/null > /dev/null

   if [ $? = 1 ] ; then 
# they differ: update file gpu-version.h
      mv ../.include/.gpu-version.h.tmp ../include/gpu-version.h
   fi
# do not update if files are the same (prevents useless recompilation)

else

# file gpu-version.h not existing: create one
   mv ../include/.gpu-version.h.tmp ../include/gpu-version.h

fi

